[package]
name = "os-workspace"
version = "0.0.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["userspace/*"]

[workspace.dependencies]
# Serializing
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
toml = "0.8.20"

# Async
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"

# OS APIs
rustix = "1"
crossterm = "0.28"
signal-hook = { version = "0.3.17", features = ["extended-siginfo"] }
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }

# Other
colored = "3"
thiserror = "2"

# Custom libraries
logger = { path = "userspace/logger" }
ipc = { path = "userspace/ipc" }
tl = { path = "userspace/tl" }

[profile.release]
opt-level = "z"
strip = true

# Packages
[[bin]]
name = "init"
path = "userspace/init"

[[bin]]
name = "serviced"
path = "userspace/serviced"
