[alias]
build-aarch64 = "build --target aarch64-unknown-linux-gnu"
baa64 = "build-aarch64"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-cc"
ar = "aarch64-unknown-linux-gnu-ar"
